### ISSUE TITLE
Copy code button

### ISSUE THREAD

**Issue by mubaraqwahab** [mubaraqwahab/mubaraqwahab.github.io#10]
**Low priority**

[From thinkdev](https://github.com/mubaraqwahab/thinkdev/blob/58f68722eb31d1fa4b825dee09aa804395d85265/utils/transforms.js#L94-L123):

```js
/**
 * @type {HTMLSubTransform}
 * Insert copy buttons next to all code blocks in the non-deck pages.
 * (I don't want copy buttons in decks because it's distracting while presenting.)
 */
function insertCopyCodeButtonsInNonDecks({document}, outputPath) {
  if (outputPath.includes("/decks/")) return


  document.querySelectorAll("pre code").forEach((code) => {
    const pre = code.parentElement
    // Make pre focusable (see issue #101)
    pre.tabIndex = -1


    const copyButton = document.createElement("button")
    copyButton.type = "button"
    // .hidden as a fallback if browser doesn't support Clipboard API.
    // The class will be removed client-side if the browser supports the API.
    copyButton.classList.add("copy-code-button", "hidden")
    copyButton.textContent = "Copy"


    const wrapper = document.createElement("div")
    wrapper.className = "copy-code-wrapper"


    wrapper.appendChild(pre.cloneNode(true))
    wrapper.appendChild(copyButton)


    // Replace the pre with the new wrapper
    pre.parentElement.replaceChild(wrapper, pre)
  })
}
```

[Also from thinkdev (CSS)](https://github.com/mubaraqwahab/thinkdev/blob/58f68722eb31d1fa4b825dee09aa804395d85265/src/main.css#L155-L195):

```css
  /* See #101 */
  .copy-code-wrapper {
    @apply relative;
    --copy-code-button-opacity: 0;
    --copy-code-button-pointer-events: none;
  }


  /* Only on hover-capable devices (e.g. desktops) */
  @media (hover: hover) {
    .copy-code-wrapper:hover {
      --copy-code-button-opacity: 1;
      --copy-code-button-pointer-events: auto;
    }
  }


  /* Only on hover-incapable devices (e.g. phones) */
  @media not all and (hover: hover) {
    .copy-code-wrapper:focus-within {
      --copy-code-button-opacity: 1;
      --copy-code-button-pointer-events: auto;
    }
  }


  .copy-code-button {
    @apply absolute top-1.5 right-1.5 border rounded text-xs font-medium px-2 py-1 select-none;
    @apply text-gray-600 dark:text-gray-400;
    @apply border-gray-300 dark:border-gray-600;
    @apply hover:text-gray-800 dark:hover:text-gray-200;
    @apply hover:border-gray-400 dark:hover:border-gray-500;
    /* Undo the hover styles when disabled */
    @apply disabled:hover:text-gray-600 disabled:dark:hover:text-gray-200;
    @apply disabled:hover:border-gray-300 disabled:dark:hover:border-gray-600;
    background-color: var(--tw-prose-pre-bg);
    opacity: var(--copy-code-button-opacity);
    pointer-events: var(--copy-code-button-pointer-events);
  }


  .copy-code-button:focus {
    --copy-code-button-opacity: 1;
    --copy-code-button-pointer-events: auto;
  }
```

See also https://github.com/mubaraqwahab/thinkdev/issues/101
